import React from "react";
import Head from "next/head";

const Heade = () => {
  return (
    <>
      <Head>
        <title>Magnacare</title>

        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

export default Heade;
